### ISSUE TITLE
code error, realtime handtrack is not working

### ISSUE THREAD

**Issue by franck34** [victordibia/handtrack.js#1]
Hi

https://victordibia.github.io/handtrack.js/#/doodle on chrome, i've got the js error below when clicking on Start Video doodle

```
react-dom.production.min.js:232 Uncaught TypeError: Cannot read property 'then' of undefined
    at t.value (Doodle.jsx:164)
    at Object.<anonymous> (react-dom.production.min.js:49)
    at p (react-dom.production.min.js:69)
    at react-dom.production.min.js:73
    at S (react-dom.production.min.js:140)
    at T (react-dom.production.min.js:169)
    at N (react-dom.production.min.js:158)
    at D (react-dom.production.min.js:232)
    at En (react-dom.production.min.js:1718)
    at Is (react-dom.production.min.js:5990)
```

Same thing for https://victordibia.github.io/handtrack.js/#/ when clicking on button Start Video

**Comment by franck34** [comment]
same on firefox portable edition, both on windows

**Comment by DanielRamosAcosta** [comment]
I'm having the same problem on Chrome 72 using Windows

**Comment by victordibia** [comment]
Thanks for the note ... looking into it now.
I confirm the issue exists ... must be a bug with a recent update to the app.

**Comment by victordibia** [comment]
@franck34 @DanielRamosAcosta 
I'v updated the demo page ... should be working now ....
P.S ... you can also experiment with the library at this  [codepen link](https://codepen.io/victordibia/pen/RdWbEY)

**Comment by franck34** [comment]
fixed. Thanks a lot ! you made a fantastic job :)
