### ISSUE TITLE
How to set the aspect ratio of a video stream?

### ISSUE THREAD

**Issue by swatty007** [victordibia/handtrack.js#10]
Im having some issues to properly set the dimensions of the video stream for a live detection.
I can correctly set the width & height of the video element. Tough its aspect ratio always stays at 3:4.

I saw that there is a commit for this to support the safari browser, but Im not using safari and would actually prefer a 16:9 resolution. Is that an expected behaviour, or do I miss something?

**Comment by victordibia** [comment]
The right way to go about this is to set the `width` and `height` (using your . 16:9 ration) of your video when you pass it to the `startVideo` method. The method is written to only set width and height to default values if you do not set these explicitly.

Let me know if that doesnt work.
