### ISSUE TITLE
Help needed to convert the model to Tflite

### ISSUE THREAD

**Issue by Suraj520** [victordibia/handtrack.js#13]
Please help me to convert the hand detection model to tflite.

**Comment by wolhandlerdeb** [comment]
I am needed help too!

**Comment by victordibia** [comment]
Hi,

I have not tried convertiing this to tflite, but here is my suggestion.

- The original model checkpoints are [here](https://github.com/victordibia/handtracking/tree/master/model-checkpoint) . There is a savedmodel and checkpoint (you can export a frozen graph from the checkpoint) format
- You can use the [tflite converte](https://www.tensorflow.org/lite/convert)r to convert the above to tflite.

Hope this helps! And ofcourse, please share what you buiild!

-V.
