### ISSUE TITLE
handTrack.load does not returns model object

### ISSUE THREAD

**Issue by ajinra020307** [victordibia/handtrack.js#14]
I have tried t work with handTrack js,,but unfortunately handTrack.load does not returns the object

**Comment by victordibia** [comment]
Hi @ajinra020307 ,

Can you paste more details on the error you observe. Note that the `load()` method returns a promise (meaning you should consume its response in a `then` block), and also this method loads the model file (which is **18.5mb** ... on slow internet connections, this may take up to two minutes). 

Please see the codepen example here for a functional example
https://codepen.io/victordibia/pen/RdWbEY
In this example, it may show "loading model" for a while ... and this message gets updated once the model is loaded.

This is one of the limitations of of using this library.

-V.
