### ISSUE TITLE
Webcam faces wrong direction

### ISSUE THREAD

**Issue by jarble** [victordibia/handtrack.js#19]
When I tried to use [this demo](https://victordibia.github.io/handtrack.js/#/) on my Microsoft Surface computer, the webcam detection was working with the front-facing webcam instead of the rear-facing webcam, so it was facing away from my keyboard. Could this demo be modified to allow switching webcams, so that it will work correctly on computers with more than one webcam?

**Comment by victordibia** [comment]
Hi @jarble,
Thanks for mentioning this. 
Yes, the demo can be extended to enable camera switching. The demo uses the html5 <video> element which happens to also support rear and front facing cameras (see https://stackoverflow.com/questions/18625007/enable-rear-camera-with-html5) .
You can try modify this codepen (i.e pass a new video object to handtrack.js) https://codepen.io/victordibia/pen/RdWbEY?editors=1010.

Once I have some time, I'll modify the demo.
-V

**Comment by SCBuergel** [comment]
Just in case anybody else comes across this: This actually works out of the box. You do not have to call the `handtrack.startVideo` method - you can start the video yourself along with settings that you may want to adjust to your application such as the `facingMode: "user"` setting. You can then simply call the `model.detect` method iteratively as is done in the example game.
Nice architecture!

**Comment by bensonruan** [comment]
I have a live demo utilized handtrak.js, the camera is working both on laptop and mobile, I had added feature to switch between front and back camera 
[https://bensonruan.com/magic-fire-in-your-hand-with-handtrack-js](https://bensonruan.com/magic-fire-in-your-hand-with-handtrack-js)
