### ISSUE TITLE
Update @tensorflow/tfjs to the latest version

### ISSUE THREAD

**Issue by johnSamilin** [victordibia/handtrack.js#3]
https://github.com/tensorflow/tfjs/releases
tfjs recently deprecated methods loadFronzenModel (as well as using .pb models) and fromPixels. The model should be converted to .json

**Comment by victordibia** [comment]
Thanks for this note and PR.
I deliberately did not use the latest version of tensorflowjs because of a data load bug in a recent version. https://github.com/tensorflow/tfjs/issues/1190#event-2207629170

Can you confirm your updates does not have these issues? 

I will also check it more when I have some time later this week.

**Comment by johnSamilin** [comment]
Yes, I've tested this code and didn't have this problem

**Comment by johnSamilin** [comment]
Hi @victordibia,
did you have a chance to check this PR?

**Comment by wolhandlerdeb** [comment]
> Yes, I've tested this code and didn't have this problem

Hi, can you explain how you convert the model. I follow the instructions of tensorflow but did not manage it.
Thanks

**Comment by johnSamilin** [comment]
@wolhandlerdeb what exactly took you into trouble?
I converted .pd to .json by running this command:
`
tensorflowjs_converter --input_format=tf_frozen_model --output_format=tensorflowjs --output_node_names='num_detections,detection_boxes,detection_scores,detection_classes,detection_masks' --saved_model_tags=serve "path-to-model.pb" .\path-to-destination-model-folder
`

**Comment by wolhandlerdeb** [comment]
> @wolhandlerdeb what exactly took you into trouble?
> I converted .pd to .json by running this command:
> `tensorflowjs_converter --input_format=tf_frozen_model --output_format=tensorflowjs --output_node_names='num_detections,detection_boxes,detection_scores,detection_classes,detection_masks' --saved_model_tags=serve "path-to-model.pb" .\path-to-destination-model-folder`

when I run this command I get this error:
TensorFlow.js model converters.: error: argument --input_format: invalid choice: 'tf_frozen_model' (choose from 'tf_hub', 'tensorflowjs', 'tf_saved_model', 'tfjs_layers_model', 'keras_saved_model', 'keras')

My version of tensorflowjs is 1.2.3. 
What is the version you are using?
 
Thanks

**Comment by wolhandlerdeb** [comment]
> > @wolhandlerdeb what exactly took you into trouble?
> > I converted .pd to .json by running this command:
> > `tensorflowjs_converter --input_format=tf_frozen_model --output_format=tensorflowjs --output_node_names='num_detections,detection_boxes,detection_scores,detection_classes,detection_masks' --saved_model_tags=serve "path-to-model.pb" .\path-to-destination-model-folder`
> 
> when I run this command I get this error:
> TensorFlow.js model converters.: error: argument --input_format: invalid choice: 'tf_frozen_model' (choose from 'tf_hub', 'tensorflowjs', 'tf_saved_model', 'tfjs_layers_model', 'keras_saved_model', 'keras')
> 
> My version of tensorflowjs is 1.2.3.
> What is the version you are using?
> 
> Thanks
Maybe you can send to me the converted model. It will help a lot

**Comment by johnSamilin** [comment]
Sure, you could find it here: https://github.com/johnSamilin/ivanovo/tree/gh-pages/data/model/json

**Comment by wolhandlerdeb** [comment]
> Sure, you could find it here: https://github.com/johnSamilin/ivanovo/tree/gh-pages/data/model/json

Thank you very much!!!

**Comment by rafinskipg** [comment]
it would be nice that handtrackjs was updated to latest version of tfjs
