### ISSUE TITLE
Codepen Demo

### ISSUE THREAD

**Issue by jeremylynch** [victordibia/handtrack.js#5]
Thought I would add the following codepen demo as a reference:

https://codepen.io/jeremylynch/pen/QPzByL?editors=1011#0

**Comment by victordibia** [comment]
Nice! Thanks for Sharing Jeremy!

You might also want to checkout this handtrack.js example on controlling a game using webcam feed ..
https://codepen.io/victordibia/full/aGpRZV

![image](https://user-images.githubusercontent.com/1547007/56833860-c04bd600-683d-11e9-8c91-02514c6df111.png)

-V.
