### ISSUE TITLE
Cannot load model

### ISSUE THREAD

**Issue by ngochai27595** [victordibia/handtrack.js#51]
Dear author,
I have face with this problem when try to do example
const video = document.getElementById('largeVideo');
        // const canvas = document.getElementById("canvas");
        // const context = canvas.getContext("2d");

        // Load the model.
        handTrack.load().then(model => {
            // detect objects in the image.
            console.log("model loaded")
            model.detect(video).then(predictions => {
                console.log('Predictions: ', predictions);
                // model.renderPredictions(predictions, canvas, context, video);
                // requestAnimationFrame(runDetection);
            });
        });

-->
"UnhandledError: Request to https://cdn.jsdelivr.net/npm/handtrackjs@latest/models/webmodel/centernet512fpn/base/model.json  failed with status code 404. Please verify this URL points to the model JSON of the model to load"
Could you help me. Thanks

**Comment by victordibia** [comment]
Hi,

Thanks for pointing this out. Its a bug with the recent release that has experimental support for centernet models.  I have fixed the bug in a new npm minor [release](https://www.npmjs.com/package/handtrackjs) but it may take a short amount of time to propagate to the jsdeliver cdn. In the mean time you can specify the `ssd320fpnlite` model when you load handtrack.js. 

```javascript

const defaultParams = { 
  modelType: "ssd320fpnlite"
};

handTrack.load(defaultParams).then(model => {
        // detect objects in the image.
        console.log("model loaded")
        model.detect(video).then(predictions => {
            console.log('Predictions: ', predictions); 
        });
});

```

**Comment by ngochai27595** [comment]
Thank you. And I have one more question. Can I hand track realtime with an available live video?
